In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from datetime import timedelta

/usr/lib/python3/dist-packages/matplotlib/__init__.py:874: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))

In [3]:
def getDates2(dft):
    sal = pd.to_datetime(dft.Hora, format="%Y-%m-%d %H:%M:%S.%f")
    dft['latency in seconds'] = (sal-pd.to_datetime(dft.Vic_date_Local, format="%Y-%m-%d %H:%M:%S.%f"))/ np.timedelta64(1, 's')
    return dft[['latency in seconds','test']]

def getLatencyPaso2_Paso1(dft):
    sal = pd.to_datetime(dft.VHPaso2, format="%Y-%m-%d %H:%M:%S.%f")
    dft['latency in seconds'] = (sal-pd.to_datetime(dft.VHPaso1, format="%Y-%m-%d %H:%M:%S.%f"))/ np.timedelta64(1, 's')
    return dft[['latency in seconds','test']]

def getLatencyPaso3_Paso1(dft):
    sal = pd.to_datetime(dft.VHPaso3, format="%Y-%m-%d %H:%M:%S.%f")
    dft['latency in seconds'] = (sal-pd.to_datetime(dft.VHPaso2, format="%Y-%m-%d %H:%M:%S.%f"))/ np.timedelta64(1, 's')
    return dft[['latency in seconds','test']]

def plotearL(col,scol):
    # plot it
    plt.rcParams['figure.dpi'] = 140
    plt.plot(col)
    plt.ylabel(scol)
    plt.show()

In [7]:
def Plotbox(mdtf1,mcolum,morder):
    plt.rcParams['figure.dpi'] = 140
    sns.boxplot(x='test', y=mcolum, data=mdtf1, order=morder)
    ax = plt.gca()
    ax.grid(True)
    plt.show()
    
def Append(mdtf1,mdtf2,mdtf3,mdtf4,mdtf5,mdtf6):
    mdtf1 = mdtf1.append(mdtf2)
    mdtf1 = mdtf1.append(mdtf3)
    mdtf1 = mdtf1.append(mdtf4)
    mdtf1 = mdtf1.append(mdtf5)
    return mdtf1.append(mdtf6)

def getDates3(dft):
    sal = pd.to_datetime(dft.dateStore, format="%Y-%m-%d %H:%M:%S.%f")
    dft['latency in seconds'] = (sal-pd.to_datetime(dft.Agre_date, format="%Y-%m-%d %H:%M:%S.%f"))/ np.timedelta64(1, 's')
    return dft[['latency in seconds','test']]
    
def AppendAndPlot(df1,df2,df3,df4,df5,df6,
                  O_column, simbol, value, morder):
    ndf = Append(df1, df2, df3, df4, df5, df6).reset_index(drop=True)
    ndf[O_column] = CastOutLayers(ndf, O_column, simbol,value)
    Plotbox(ndf,O_column,morder)

def CastOutLayers(mdtf1, column, lowerorgreater,mlimit):
    aux = []
    for row in mdtf1[column]:
        if type(row) is str:
            row =row.replace(".", "")
        if lowerorgreater == "<":
            if float(row) > mlimit:
                aux.append(mlimit)
            else:
                aux.append(float(row))
        elif lowerorgreater == ">":
            if float(row) < mlimit:
                aux.append(mlimit)
            else:
                aux.append(float(row))
    return aux

In [5]:
dft25

,timestamp1,Hora,timestamp2,Hpaso21,Hpaso22,test
0,2019-01-22 22:23:11.545964,2019-01-22 22:23:31.756,2019-01-22 22:23:31.585897,NaN,NaN,25
1,2019-01-22 22:23:11.570137,2019-01-22 22:23:31.836,2019-01-22 22:23:31.598762,NaN,NaN,25
2,2019-01-22 22:23:11.545172,2019-01-22 22:23:31.757,2019-01-22 22:23:31.585202,NaN,NaN,25
3,2019-01-22 22:23:11.554391,2019-01-22 22:23:31.765,2019-01-22 22:23:31.595271,NaN,NaN,25
4,2019-01-22 22:23:11.553827,2019-01-22 22:23:31.761,2019-01-22 22:23:31.594507,NaN,NaN,25
5,2019-01-22 22:23:11.550516,2019-01-22 22:23:31.755,2019-01-22 22:23:31.590189,NaN,NaN,25
6,2019-01-22 22:23:11.547911,2019-01-22 22:23:31.756,2019-01-22 22:23:31.587732,NaN,NaN,25
7,2019-01-22 22:23:11.549490,2019-01-22 22:23:31.773,2019-01-22 22:23:31.589190,NaN,NaN,25
8,2019-01-22 22:23:11.551007,2019-01-22 22:23:31.757,2019-01-22 22:23:31.590674,NaN,NaN,25
9,2019-01-22 22:23:11.572030,2019-01-22 22:23:31.758,2019-01-22 22:23:31.604158,NaN,NaN,25
10,2019-01-22 22:23:11.547433,2019-01-22 22:23:31.754,2019-01-22 22:23:31.587256,NaN,NaN,25
11,2019-01-22 22:23:11.556200,2019-01-22 22:23:31.755,2019-01-22 22:23:31.596766,NaN,NaN,25
12,2019-01-22 22:23:11.550017,2019-01-22 22:23:31.775,2019-01-22 22:23:31.589687,NaN,NaN,25
13,2019-01-22 22:23:11.557227,2019-01-22 22:23:31.756,2019-01-22 22:23:31.597749,NaN,NaN,25
14,2019-01-22 22:23:11.548447,2019-01-22 22:23:31.756,2019-01-22 22:23:31.588225,NaN,NaN,25
15,2019-01-22 22:23:11.546441,2019-01-22 22:23:31.756,2019-01-22 22:23:31.586317,NaN,NaN,25
16,2019-01-22 22:23:11.555661,2019-01-22 22:23:31.759,2019-01-22 22:23:31.596282,NaN,NaN,25
17,2019-01-22 22:23:11.548970,2019-01-22 22:23:31.755,2019-01-22 22:23:31.588707,NaN,NaN,25
18,2019-01-22 22:23:11.570910,2019-01-22 22:23:33.321,2019-01-22 22:23:31.602936,NaN,NaN,25
19,2019-01-22 22:23:11.557777,2019-01-22 22:23:33.323,2019-01-22 22:23:31.598223,NaN,NaN,25
20,2019-01-22 22:23:11.546933,2019-01-22 22:23:33.322,2019-01-22 22:23:31.586777,NaN,NaN,25
21,2019-01-22 22:23:11.554909,2019-01-22 22:23:33.420,2019-01-22 22:23:31.595794,NaN,NaN,25
22,2019-01-22 22:23:11.556732,2019-01-22 22:23:33.433,2019-01-22 22:23:31.597264,NaN,NaN,25
23,2019-01-22 22:23:11.571483,2019-01-22 22:23:33.674,2019-01-22 22:23:31.603646,NaN,NaN,25
24,2019-01-22 22:23:11.572549,2019-01-22 22:23:33.675,2019-01-22 22:23:31.604717,NaN,NaN,25
25,2019-01-22 22:24:11.663923,2019-01-22 22:24:31.798,2019-01-22 22:24:31.698327,NaN,NaN,25
26,2019-01-22 22:24:11.655687,2019-01-22 22:24:31.992,2019-01-22 22:24:31.685307,NaN,NaN,25
27,2019-01-22 22:24:11.657918,2019-01-22 22:24:31.807,2019-01-22 22:24:31.687552,NaN,NaN,25
28,2019-01-22 22:24:11.656427,2019-01-22 22:24:31.807,2019-01-22 22:24:31.686056,NaN,NaN,25
29,2019-01-22 22:24:11.654937,2019-01-22 22:24:31.805,2019-01-22 22:24:31.684562,NaN,NaN,25
...,...,...,...,...,...,...
220,2019-01-22 22:31:12.320760,2019-01-22 22:31:33.751,2019-01-22 22:31:32.350238,NaN,NaN,25
221,2019-01-22 22:31:12.321254,2019-01-22 22:31:33.873,2019-01-22 22:31:32.350744,NaN,NaN,25
222,2019-01-22 22:31:12.324854,2019-01-22 22:31:33.870,2019-01-22 22:31:32.357740,NaN,NaN,25
223,2019-01-22 22:31:12.318034,2019-01-22 22:31:34.177,2019-01-22 22:31:32.347437,NaN,NaN,25
224,2019-01-22 22:31:12.325540,2019-01-22 22:31:34.290,2019-01-22 22:31:32.358306,NaN,NaN,25
225,2019-01-22 22:32:12.405657,2019-01-22 22:32:32.545,2019-01-22 22:32:32.428999,NaN,NaN,25
226,2019-01-22 22:32:12.406664,2019-01-22 22:32:32.563,2019-01-22 22:32:32.430105,NaN,NaN,25
227,2019-01-22 22:32:12.405908,2019-01-22 22:32:32.563,2019-01-22 22:32:32.429264,NaN,NaN,25
228,2019-01-22 22:32:12.402725,2019-01-22 22:32:32.565,2019-01-22 22:32:32.425933,NaN,NaN,25
229,2019-01-22 22:32:12.404106,2019-01-22 22:32:32.562,2019-01-22 22:32:32.427470,NaN,NaN,25
230,2019-01-22 22:32:12.403858,2019-01-22 22:32:32.559,2019-01-22 22:32:32.427213,NaN,NaN,25
231,2019-01-22 22:32:12.405415,2019-01-22 22:32:32.554,2019-01-22 22:32:32.428747,NaN,NaN,25
232,2019-01-22 22:32:12.404348,2019-01-22 22:32:32.556,2019-01-22 22:32:32.427718,NaN,NaN,25
233,2019-01-22 22:32:12.410382,2019-01-22 22:32:32.552,2019-01-22 22:32:32.441525,NaN,NaN,25
234,2019-01-22 22:32:12.404832,2019-01-22 22:32:32.550,2019-01-22 22:32:32.428225,NaN,NaN,25
235,2019-01-22 22:32:12.407919,2019-01-22 22:32:32.548,2019-01-22 22:32:32.431374,NaN,NaN,25
236,2019-01-22 22:32:12.406157,2019-01-22 22:32:32.545,2019-01-22 22:32:32.429547,NaN,NaN,25
237,2019-01-22 22:32:12.403369,2019-01-22 22:32:32.547,2019-01-22 22:32:32.426707,NaN,NaN,25
238,2019-01-22 22:32:12.406923,2019-01-22 22:32:32.651,2019-01-22 22:32:32.430356,NaN,NaN,25
239,2019-01-22 22:32:12.403147,2019-01-22 22:32:32.645,2019-01-22 22:32:32.426439,NaN,NaN,25
240,2019-01-22 22:32:12.404587,2019-01-22 22:32:32.649,2019-01-22 22:32:32.427968,NaN,NaN,25
241,2019-01-22 22:32:12.405157,2019-01-22 22:32:32.648,2019-01-22 22:32:32.428486,NaN,NaN,25
242,2019-01-22 22:32:12.403618,2019-01-22 22:32:32.645,2019-01-22 22:32:32.426964,NaN,NaN,25
243,2019-01-22 22:32:12.410092,2019-01-22 22:32:33.495,2019-01-22 22:32:32.441264,NaN,NaN,25
244,2019-01-22 22:32:12.406406,2019-01-22 22:32:33.734,2019-01-22 22:32:32.429839,NaN,NaN,25
245,2019-01-22 22:32:12.407166,2019-01-22 22:32:33.889,2019-01-22 22:32:32.430609,NaN,NaN,25
246,2019-01-22 22:32:12.409617,2019-01-22 22:32:33.889,2019-01-22 22:32:32.440945,NaN,NaN,25
247,2019-01-22 22:32:12.407410,2019-01-22 22:32:33.892,2019-01-22 22:32:32.430868,NaN,NaN,25
248,2019-01-22 22:32:12.407668,2019-01-22 22:32:34.48,2019-01-22 22:32:32.431123,NaN,NaN,25
249,2019-01-22 22:32:12.410628,2019-01-22 22:32:34.277,2019-01-22 22:32:32.441795,NaN,NaN,25

In [4]:
dft25 = pd.read_csv('latencyRaspberry/25_4.csv')
dft25  ["test"]= "25"

dft50 = pd.read_csv('latencyRaspberry/50_4.csv')
dft50  ["test"]= "50"

dft75 = pd.read_csv('latencyRaspberry/75_4.csv')
dft75  ["test"]= "75"

dft100 = pd.read_csv('latencyRaspberry/100_4.csv')
dft100  ["test"]= "100"

dft125 = pd.read_csv('latencyRaspberry/125_15.csv')
dft125  ["test"]= "125"

dft150 = pd.read_csv('latencyRaspberry/150_15.csv')
dft150  ["test"]= "150"

AttributeError: 'DataFrame' object has no attribute 'VHPaso2'